### ISSUE TITLE
Does not work on Apple Sillicon

### ISSUE THREAD

**Issue by PringlePot** [tauri-apps/tauricon#79]
Due to this tool depending on `optipng` it doesn't work with apple sillicon. This is due to optipng using operations that arent available on arm.

**Comment by FabianLars** [comment]
We won't make any major changes to tauricon anymore since the rust rewrite for tauri 1.1 is complete, see https://github.com/tauri-apps/tauri/pull/4992.
On top of that there likely isn't even a viable alternative we could use here because (js) image libraries seem to be quite a mess :(

If you have the time you could check if the rust rewrite works on apple silicon (i don't have access to it myself), by installing the tauri cli like this `cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch feat/tauricon` and then try it out by running `cargo tauri icon path/to/the/input/icon.png`

**Comment by PringlePot** [comment]
Thanks! Its great that you guys are recoding everything in rust :)
