### ISSUE TITLE
Generating from square icons fails due to strict transparency check

### ISSUE THREAD

**Issue by akozhemiakin** [tauri-apps/tauricon#80]
It seems that because of the following strict check it is impossible to convert perfectly square icons, because, obviously, they have no transparent pixels. Could we just remove this block or at least provide some CLI flag to disable it?

https://github.com/tauri-apps/tauricon/blob/5eea916a4a8e13aa41a943beaa7b4b71977e190d/src/tauricon.ts#L94-L103

**Comment by FabianLars** [comment]
The problem is that the libs we have to use can mess up the output if they don't detect the images as transparent. On top of that we won't make any major changes (or changes that _can_ break stuff) to tauricon anymore since the rust rewrite is complete and waiting for tauri's 1.1 release, see https://github.com/tauri-apps/tauri/pull/4992. The new version doesn't have this check since it can add alpha channels itself more reliable from my testing.

**Comment by akozhemiakin** [comment]
Ok, thx for quick reply.

Dirty hack for those facing the same issue: make one pixel a little bit transparent.
